//auth types
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const LOGOUT_USER_OUT = "LOGOUT_USER_OUT";
export const REGISTER_START = "REGISTER_START";

// contact types
export const ADD_CONTACT_START = "ADD_CONTACT_START";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";
export const GET_CONTACTS_START = "GET_CONTACTS_START";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const DELETE_CONTACT_START = "DELETE_CONTACT_START";
export const GET_CONTACTS_ERROR = "GET_CONTACTS_ERROR";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";
export const STAR_CONTACT_START = "STAR_CONTACT_START";
export const STAR_CONTACT_SUCCESS = "STAR_CONTACT_SUCCESS";
export const STAR_CONTACT_ERROR = "STAR_CONTACT_ERROR";
export const EDIT_CONTACT_START = "EDIT_CONTACT_START";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_ERROR = "EDIT_CONTACT_ERROR";
export const CLEAR_EDIT_CONTACT = "CLEAR_EDIT_CONTACT";
export const SEARCH_CONTACTS = "SEARCH_CONTACTS";
